name: Build
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry --version
      - run: export PATH="/root/.local/bin:$PATH"
      - run: poetry install
      - run: poetry run flake8
      - run: poetry build
      - run: |
          poetry run pytest --junit-xml=cover/test-results.xml \
            --cov=hello_python \
            --cov-report term-missing  \
            --cov-report xml:cover/coverage.xml \
            --cov-report html:cover/coverage.html \
            --cov-report lcov:cover/coverage.info
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: ./dist/
