name: Build
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: export PATH="/root/.local/bin:$PATH"
      - run: poetry install
      - run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/
